spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  application:
   name: ingredient-service

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/, http://eureka2.tacocloud.com:8762/eureka/

tacocloud:
  email:
    host: tacocloud.com
